[features]
seeds = false
[programs.localnet]
signatures = "J9UWzu1hScBJkw4MLqrfQvKMjyFj3jAKJWGASYmEnvFn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/nisu/.config/solana/id.json"

[scripts]
test-eth-sig = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/eth_signatures.ts"
test-sig = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/signatures.ts"
